<?php
/**PHP
*------------------------------------------------------------------------------
* Steffen Berkenkamp
* copyright (c) 2022 Steffen Berkenkamp, all rights reserved
*
* this file may not be redistributed in whole or significant part
* and is subject to the Steffen Berkenkamp license.
*------------------------------------------------------------------------------
*/


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE);
include_once("classes/getClass.php");
function utf8_converter($array){
    array_walk_recursive($array, function(&$item, $key){
        if(!mb_detect_encoding($item, 'utf-8', true)){
            $item = utf8_encode($item);
        }
    });
    return $array;
}
//$nummer = $_GET['type'];
//$data =  DATA::waage_kost();
//print_r($data);
//echo('ok');

?>

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Waage</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <style>
  .ui-autocomplete {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  list-style: none;
  font-size: 14px;
  text-align: left;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  background-clip: padding-box;
}

.ui-autocomplete > li > div {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333333;
  white-space: nowrap;
}

.ui-state-hover,
.ui-state-active,
.ui-state-focus {
  text-decoration: none;
  color: #262626;
  background-color: #f5f5f5;
  cursor: pointer;
}

.ui-helper-hidden-accessible {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
.ui-widget.success-dialog {
    font-family: Verdana,Arial,sans-serif;
    font-size: .8em;
}

.ui-widget-content.success-dialog {
    background: #F9F9F9;
    border: 1px solid #90d93f;
    color: #222222;
}

.ui-dialog.success-dialog {
    left: 0;
    outline: 0 none;
    padding: 0 !important;
    position: absolute;
    top: 0;
}

.ui-dialog.success-dialog .ui-dialog-content {
    background: none repeat scroll 0 0 transparent;
    border: 0 none;
    overflow: auto;
    position: relative;
    padding: 0 !important;
    margin: 0;
}

.ui-dialog.success-dialog .ui-widget-header {
    background: #b0de78;
    border: 0;
    color: #fff;
    font-weight: normal;
}

.ui-dialog.success-dialog .ui-dialog-titlebar {
    padding: 0.1em .5em;
    position: relative;
    font-size: 1em;
}
.highlight {
   background-color: #a8cb17;
}
</style>

</head>
<body>
 <div class="container">
 <br>
 <h1>Gewichtserfassung Geiger Textil</h1>
 <br>
 <div class="row g-3">
  <div class="col-sm-7">
    <input id="kunde" type="text" class="form-control" placeholder="Kunde" aria-label="Kunde" autofocus>
  </div>
  </div>
  <div id="kost" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Kostenstellen</h5>

        </div>
        <div class="modal-body">
  <table class="table table-bordered"  >
    <thead>
    <tr>
     <th scope="col">Kostenstelle</th>
     <th scope="col">Bezeichnung</th>
     </tr>
      </thead>
      <tbody id="kostenst">

      </tbody>
  </table>
</div>
     <div class="modal-footer">

       <button id="schle" type="button" class="btn btn-success" data-dismiss="modal">OK</button>
     </div>
   </div>
 </div>
</div>
  <div class="col-sm">
    <input id="kostst" type="text" class="form-control" placeholder="Kostenstelle" aria-label="Kostenstelle">
  </div>
  <div class="col-sm">
    <input id="kostste" type="text" class="form-control" placeholder="Artikel" aria-label="Artikel">
  </div>
  <div id="koste" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Kostenstellen</h5>

        </div>
        <div class="modal-body">
    <table class="table table-bordered"  >
      <thead>
      <tr>
       <th scope="col">ArtikelNr</th>
       <th scope="col">Bezeichnung</th>
       </tr>
        </thead>
        <tbody id="arti">

        </tbody>
    </table>
  </div>
       <div class="modal-footer">

         <button id="schle" type="button" class="btn btn-success" data-dismiss="modal">OK</button>
       </div>
     </div>
   </div>
  </div>



 </div>
 <script type="text/javascript">

  $( function() {
       var availableTags = ['SFS SERVICE FÜR SENIOREN GMBH', 'SFS SERVICE FÜR SENIOREN GMBH', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'ALTERA FRANKENTHAL', 'PH EFRINGEN-KIRCHEN', 'HAUS AM GUGEL', 'ST. MARIENHAUS BS', 'ALPENBLICK', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'PFLEGEHEIM ZELL I.W.', 'HAUS EICHBERG', 'PH BRUNNENWIESEN', 'HVB LAUBENHEIMER RI.', 'EDELBERG BAD FRIEDRICHSH.', 'EDELBERG IFFEZHEIM', 'VITALIS SCHORNDORF', 'VITALIS PLOCHINGEN', 'VITALIS PLOCHINGEN', 'VITALIS TUTTLINGEN', 'ÖSCHELBRONN KLINIK', 'EDELBERG PFINZTAL', 'EDELBERG OBERDERDINGEN', 'EDELBERG LUDWIGSBURG', 'EDELBERG LAUFFEN', 'EDELBERG KERNEN', 'EDELBERG EPPELHEIM', 'EDELBERG BIETIGHEIM', 'EDELBERG BELLHEIM', 'EDELBERG KARLSRUHE', 'EDELBERG WETZGAUERBERG', 'EDELBERG STUTENSEE', 'EDELBERG NEULUßHEIM', 'EDELBERG WEINGARTEN', 'SFS SERVICE FÜR SENIOREN GMBH', 'WIECHS (MPH)', 'BÜRGERHEIM (BHR)', 'JESTETTEN SEN.WOHN.', 'IM BRÜEL', 'RHEINWEILER SCHLOSS', 'HVB KOBLENZ', 'HVB NIEDERNHAUSEN', 'HVB ULMEN', 'HVB LIMBURG', 'HVB VILLMAR', 'HVB WALLMEROD', 'HVB SCHÖFFENGRUND', 'LOT GEIGER TEXTIL', 'SENEVITA ZOLLIKOFEN', 'SENEVITA LIMMATFELD DIETIKON', 'SENEVITA PRATTELN', 'SENEVITA SPREITENBACH', 'SENEVITA OLTEN', 'SENEVITA PANORAMA', 'SENEVITA BÜMPLIZ', 'SENEVITA DAMMWEG', 'SENEVITA GELLERTBLICK BASEL', 'VITALIS SPEYER', 'VITALIS LINGENFELD', 'VITALIS FRANKENTHAL', 'VITALIS BRUCHMÜHLBACH', 'VITALIS KLARENTHAL', 'VITALIS SAARBRÜCKEN', 'VITALIS RODALBEN', 'VITALIS ÖSTRINGEN', 'VITALIS PIRMASENS', 'GENERATIONENHAUS', 'BAAR PFLEGEZENTRUM', 'PHW WEIL', 'HERTEN JOSEFSHAUS', 'WOHNANLAGE RÖTE', 'BRÄUNLINGEN SZ', 'AWO VS', 'ST. CYRIAK', 'MARGARETENHEIM LÖRRACH', 'MARGARETENHEIM LÖRRACH', 'GEVITA MÜLLHEIM', 'GEVITA LÖRRACH', 'COLUMBAN', 'SUNCHEMICAL HUNINGUE', 'VITA ZAHNFABRIK', 'WARTENBERG GEISINGEN', 'LOT GEIGER TEXTIL', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'DIVERSE A-Z DEUTSCHLAND', 'GATE GOURMET ZÜRICH', 'JOWA ECUBLENS', 'JOWA GOSSAU', 'JOWA GOSSAU', 'JOWA GRÄNICHEN', 'JOWA S. ANTONINO', 'JOWA HB AARE', 'JOWA VOLKETSWIL', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'GATE GOURMET GENF', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'GATE GOURMET GENF', 'GEIGER TEXTIL', 'MONDELEZ BLUDENZ', 'MONDELEZ BLUDENZ', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'GATE GOURMET GENF', 'GEIGER TEXTIL', 'EDELWEISS', 'EDELWEISS', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'NOVARTIS PHARMA WEHR', 'NOVARTIS STEIN', 'MUSTERTEILE AUTOSTORE', 'TRAGETEST REINRAUM', 'PAPIERFA. LOUISENTHAL', 'PAUL SCHERRER INSTITUT', 'MAX-PLANCK-INSTITUT', 'SPLENDIDA', 'HELMHOLTZ-INSTITUT', 'NB TECHNOLOGIES', 'VISION IN AUTOMATION', 'VASCULAR', 'VASCOMED', 'UNIPA KUNSTSTOFFTECHNIK', 'A+M', 'SPITAL LIMMATTAL', 'GP GRENZACH PRODUKTION', 'WELEDA SCHWÄB. GMÜND', 'NOVARTIS ST. JOHANN', 'DSM SISSELN BAU 340', 'DOMACO', 'BIOGEN CBRE', 'TAKEDA NEUCHATEL ISS', 'PENTAPHARM', 'APOTHEKE WELEDA', 'SPACE TECH', 'GP GRENZACH PRODUKTION', 'SALINA MEDIZIN', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'ACINO PFEFFINGERRING', 'ACINO LIESBERG', 'SEMINARHOTEL SCHÜTZEN', 'GATE GOURMET ZÜRICH', 'HOTEL EDEN', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'KURVERWALTUNG SÄCKINGEN', 'VITA - BALLYWEG', 'KINDERGARTEN GALLUSTURM', 'REHA-ZENTRUM BAD DÜRRHEIM', 'ST. ELISABETHEN KH', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'SPITAL LIMMATTAL', 'STADTVERW. BS', 'BIS PROZESSTECHNIK', 'JOWA ECUBLENS', 'JOWA GOSSAU', 'JOWA GRÄNICHEN', 'JOWA S. ANTONINO', 'JOWA BUCHS', 'JOWA HB AARE', 'JOWA VOLKETSWIL', 'WELEDA AG ARLESHEIM', 'BILFINGER ZOFINGEN', 'INTERTEK', 'KS SCHAFFHAUSEN', 'PSYCHIATRIE BREITENAU', 'PSYCHIATRIE BREITENAU', 'INGA WIECHS (MPH)', 'HOTEL SCHIFF', 'NOVARTIS ST. JOHANN', 'UNIVERSITÄTSKLINIKUM FREIB', 'UNIVERSITÄTSKLINIKUM FREIB', 'KB KLINIK BADENWEILER', 'UMICORE RHEINFELDEN', 'UMICORE BAD SÄCKINGEN', 'MIGROS BASEL', 'LOT GEIGER TEXTIL', 'HL-KANTINE', 'HL-KANTINE', 'DSM SISSELN', 'DSM KAISERAUGST', 'HAGO', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'LINDT&SPRÜ KILCHBERG', 'EMMI GOSSAU DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI LANDQUART', 'EMMI EMMEN', 'EMMI KIRCHBERG', 'EMMI LANGNAU', 'EMMI OSTERMUNDIGEN', 'SEDUS STOLL AG', 'STADTWERKE WT', 'HERTEN JOSEFSHAUS', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'GEVITA MÜLLHEIM', 'GEVITA LÖRRACH', 'HUNTSMAN BAD SÄCKINGEN', 'WASCHTESTS INTERN', 'EDELWEISS', 'EDELWEISS', 'KB KLINIK BADENWEILER', 'EDELWEISS', 'EDELWEISS', 'UMICORE RHEINFELDEN', 'JOWA VOLKETSWIL', 'LINDT&SPRÜ OLTEN', 'LINDT&SPRÜ KILCHBERG', 'GATE GOURMET ZÜRICH', 'GATE GOURMET GENF', 'JOWA ECUBLENS', 'JOWA GOSSAU', 'JOWA GRÄNICHEN', 'JOWA S. ANTONINO', 'JOWA BUCHS', 'JOWA VOLKETSWIL', 'COOP BÄCKEREI BERN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'MONDELEZ BLUDENZ', 'MONDELEZ BLUDENZ', 'HL-KANTINE', 'HL-KANTINE', 'LINDT&SPRÜ KILCHBERG', 'VITA - BALLYWEG', 'VITA - BALLYWEG', 'VITA - BALLYWEG', 'GP GRENZACH PRODUKTION', 'SOLE UNO', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'ACINO PFEFFINGERRING', 'HOTEL EDEN', 'GEIGER TEXTIL', 'BASF GRENZACH', 'NOVARTIS PHARMA WEHR', 'ST. ELISABETHEN KH', 'GLATT PHARMAC.', 'DIVERSE A-Z DEUTSCHLAND', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'SPITAL LIMMATTAL', 'BIS PROZESSTECHNIK', 'NOVARTIS STEIN', 'NOVARTIS SCHWEIZERHALLE', 'JOWA ECUBLENS', 'JOWA GOSSAU', 'SYNGENTA KAISTEN', 'BILFINGER ZOFINGEN', 'WELEDA SCHWÄB. GMÜND', 'NOVARTIS KLYBECK', 'NOVARTIS ST. JOHANN', 'FMI FRIEDRICH MIESCHER INSTIT.', 'UMICORE RHEINFELDEN', 'LOT GEIGER TEXTIL', 'DSM VILLAGE NEUF', 'HL-KANTINE', 'DSM SISSELN', 'DSM KAISERAUGST', 'ESCIENTIA', 'SYNGENTA MUTTENZ', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'HERTEN JOSEFSHAUS', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'RUCK GMBH', 'BASF ROSENTAL', 'BASF KAISTEN', 'BASF SCHWEIZERHALLE', 'BASF MONTHEY', 'BASF KLYBECK', 'HUNTSMAN KLYBECK', 'HUNTSMAN MONTHEY', 'HUNTSMAN BAD SÄCKINGEN', 'RHEINFELDEN KH', 'LANDKLINIK', 'ALTERA FRANKENTHAL', 'ALTERA FRANKENTHAL', 'OP-BETREIBER SECONIA', 'SCHMIEDHOF', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'HOTZENPLOTZ KLINIK', 'PH EFRINGEN-KIRCHEN', 'PH EFRINGEN-KIRCHEN', 'RHEIN JURA KLINIK', 'HÄNSLEHOF', 'HAUS AM GUGEL', 'SPITAL WALDSHUT', 'ST. MARIENHAUS BS', 'ST. MARIENHAUS BS', 'RHEUMAKL.', 'WEHRAWALD', 'REHA-ZENTRUM BAD DÜRRHEIM', 'ST.FRANZISKUS', 'ALPENBLICK', 'ALPENBLICK', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'PRAXISKLINIK RHEINF.', 'KLINIKEN LOERRACH MBK', 'DIAKONISSEN-KH RÜPPURR', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'SPITAL LIMMATTAL', 'SPITAL LIMMATTAL', 'MZ BRUGG', 'PFLEGEHEIM ZELL I.W.', 'PFLEGEHEIM ZELL I.W.', 'AWO WUTOESCHINGEN', 'AWO WUTOESCHINGEN', 'HAUS EICHBERG', 'HAUS EICHBERG', 'PH BRUNNENWIESEN', 'PH BRUNNENWIESEN', 'VINCENTIUS STEINHÄUSER', 'MARIENKLINIK KARLSRUHE', 'VINCENTIUS SÜDENDSTR.', 'KS SCHAFFHAUSEN', 'PSYCHIATRIE BREITENAU', 'HAUS G - WIECHS(MPH)', 'DR. SCHWARTZKOPFF', 'REHACITY BASEL', 'DRK KV TUTTLINGEN', 'HEGAU PZ', 'RHEINGARTEN', 'HVB LAUBENHEIMER RI.', 'HVB LAUBENHEIMER RI.', 'EDELBERG BAD FRIEDRICHSH.', 'EDELBERG BAD FRIEDRICHSH.', 'EDELBERG IFFEZHEIM', 'EDELBERG IFFEZHEIM', 'VITALIS SCHORNDORF', 'VITALIS SCHORNDORF', 'VITALIS PLOCHINGEN', 'VITALIS PLOCHINGEN', 'VITALIS TUTTLINGEN', 'VITALIS TUTTLINGEN', 'ÖSCHELBRONN KLINIK', 'ST. GEORG PRIVATKL.', 'UNIVERSITÄTSKLINIKUM FREIB', 'EDELBERG PFINZTAL', 'EDELBERG PFINZTAL', 'EDELBERG OBERDERDINGEN', 'EDELBERG OBERDERDINGEN', 'EDELBERG LUDWIGSBURG', 'EDELBERG LUDWIGSBURG', 'EDELBERG LAUFFEN', 'EDELBERG LAUFFEN', 'EDELBERG KERNEN', 'EDELBERG KERNEN', 'EDELBERG EPPELHEIM', 'EDELBERG EPPELHEIM', 'EDELBERG BIETIGHEIM', 'EDELBERG BIETIGHEIM', 'EDELBERG BELLHEIM', 'EDELBERG BELLHEIM', 'EDELBERG KARLSRUHE', 'EDELBERG KARLSRUHE', 'EDELBERG WETZGAUERBERG', 'EDELBERG WETZGAUERBERG', 'EDELBERG STUTENSEE', 'EDELBERG STUTENSEE', 'EDELBERG NEULUßHEIM', 'EDELBERG NEULUßHEIM', 'EDELBERG WEINGARTEN', 'EDELBERG WEINGARTEN', 'SFS SERVICE FÜR SENIOREN GMBH', 'SFS SERVICE FÜR SENIOREN GMBH', 'INGA RHEINWEILER', 'KB KLINIK BADENWEILER', 'WIECHS (MPH)', 'FFA HÜFINGEN', 'BÜRGERHEIM (BHR)', 'BÜRGERHEIM (BHR)', 'IM BRÜEL', 'IM BRÜEL', 'HUMANITAS', 'RHEINWEILER SCHLOSS', 'RHEINWEILER SCHLOSS', 'HVB KOBLENZ', 'HVB KOBLENZ', 'HVB NIEDERNHAUSEN', 'HVB NIEDERNHAUSEN', 'HVB ULMEN', 'HVB ULMEN', 'HVB LIMBURG', 'HVB LIMBURG', 'HVB VILLMAR', 'HVB VILLMAR', 'HVB WALLMEROD', 'HVB WALLMEROD', 'HVB SCHÖFFENGRUND', 'HVB SCHÖFFENGRUND', 'LOT GEIGER TEXTIL', 'SENEVITA EBIKON', 'SENEVITA ZOLLIKOFEN', 'SENEVITA ZOLLIKOFEN', 'SENEVITA LIMMATFELD DIETIKON', 'SENEVITA LIMMATFELD DIETIKON', 'SENEVITA PRATTELN', 'SENEVITA PRATTELN', 'SENEVITA SPREITENBACH', 'SENEVITA SPREITENBACH', 'SENEVITA OLTEN', 'SENEVITA OLTEN', 'SENEVITA AARAU', 'SENEVITA PANORAMA', 'SENEVITA PANORAMA', 'SENEVITA BÜMPLIZ', 'SENEVITA BÜMPLIZ', 'SENEVITA DAMMWEG', 'SENEVITA DAMMWEG', 'SENEVITA GELLERTBLICK BASEL', 'SENEVITA GELLERTBLICK BASEL', 'VITALIS SPEYER', 'VITALIS SPEYER', 'VITALIS LINGENFELD', 'VITALIS LINGENFELD', 'VITALIS FRANKENTHAL', 'VITALIS FRANKENTHAL', 'VITALIS BRUCHMÜHLBACH', 'VITALIS BRUCHMÜHLBACH', 'VITALIS KLARENTHAL', 'VITALIS KLARENTHAL', 'VITALIS SAARBRÜCKEN', 'VITALIS SAARBRÜCKEN', 'VITALIS RODALBEN', 'VITALIS RODALBEN', 'VITALIS ÖSTRINGEN', 'VITALIS ÖSTRINGEN', 'VITALIS PIRMASENS', 'VITALIS PIRMASENS', 'GENERATIONENHAUS', 'GENERATIONENHAUS', 'HOCHHAUS H21 BAAR', 'BAAR PFLEGEZENTRUM', 'BAAR PFLEGEZENTRUM', 'RENNBAHNKLINIK', 'SCHÖMBERG FACHKLINIK', 'SCHETTLER KLINIK', 'WEIL KLINIK', 'BAD HERRENALB KLINIK', 'SIGMA ZENTRUM', 'DOROW CLINIC LÖRRACH', 'DOROW CLINIC WALDSHUT MVZ', 'OBERBERGKLINIK', 'LUISENKLINIK', 'LUISENKLINIK-KIJU', 'PHW WEIL', 'PHW WEIL', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'DIAKONISSENANSTALT PFLEGE', 'BRÄUNLINGEN SZ', 'AWO VS', 'AWO VS', 'MALTESER', 'ST. CYRIAK', 'ST. CYRIAK', 'MARGARETENHEIM LÖRRACH', 'MARGARETENHEIM LÖRRACH', 'KKH SCHOPFHEIM', 'GEVITA MÜLLHEIM', 'GEVITA LÖRRACH', 'GEVITA LÖRRACH', 'KAEFER', 'COLUMBAN', 'COLUMBAN', 'BASF KLYBECK', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'REHAKLINIK RHEINFELDEN', 'SEMINARHOTEL SCHÜTZEN', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'HOTEL EDEN', 'ACINO DORNACHER', 'GEIGER TEXTIL', 'RHEUMAKL.', 'KLINIKEN LOERRACH MBK', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WELEDA AG ARLESHEIM', 'HOTEL SCHIFF', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'RÖSSLE LANDGASTHOF', 'KB KLINIK BADENWEILER', 'LOT GEIGER TEXTIL', 'HL-KANTINE', 'HL-KANTINE', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'WOHNANLAGE RÖTE', 'BASF KAISTEN', 'UMICORE RHEINFELDEN', 'SOLE UNO', 'ST. ELISABETHEN KH', 'SPITAL LIMMATTAL', 'MZ BRUGG', 'MZ BRUGG', 'KS SCHAFFHAUSEN', 'DRK KV TUTTLINGEN', 'UNIVERSITÄTSKLINIKUM FREIB', 'INGA RHEINWEILER', 'LOT GEIGER TEXTIL', 'BAD HERRENALB SERVICE', 'AHRENS TEXTIL-SERVICE GMBH', 'HIMMELSPFORTE', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'DIAKONISSEN-KH RÜPPURR', 'SPITAL LIMMATTAL', 'MIDOR', 'WELEDA SCHWÄB. GMÜND', 'RHEINGARTEN', 'INGA RHEINWEILER', 'JESTETTEN SEN.WOHN.', 'LOT GEIGER TEXTIL', 'PHW WEIL', 'EMMI GOSSAU DHL', 'BRÄUNLINGEN SZ', 'AWO VS', 'MARGARETENHEIM LÖRRACH', 'VASCOMED', 'CLEAN', 'RHEINWEILER SCHLOSS', 'WIECHS (MPH)', 'FISHER ALLSCHWIL', 'RHEINFELDEN KH', 'LORENZ GMBH', 'SWISS INTERNATIONAL', 'SWISS GENF', 'SWISS ZÜRICH', 'LANDKLINIK', 'LANDKLINIK', 'LANDKLINIK', 'AGILENT TECHNOLOGIES', 'ALTERA FRANKENTHAL', 'GP GRENZACH PRODUKTION', 'REHAKLINIK RHEINFELDEN', 'ACINO PFEFFINGERRING', 'HOTZENPLOTZ KLINIK', 'ACINO LIESBERG', 'DELIPET', 'PH EFRINGEN-KIRCHEN', 'RHEIN JURA KLINIK', 'HÄNSLEHOF', 'HÄNSLEHOF', 'BASF GRENZACH', 'HAUS AM GUGEL', 'SPITAL WALDSHUT', 'ST. MARIENHAUS BS', 'RHEUMAKL.', 'WEHRAWALD', 'NOVARTIS PHARMA WEHR', 'VITA ZAHNFABRIK', 'VITA - BALLYWEG', 'REHA-ZENTRUM BAD DÜRRHEIM', 'ST.FRANZISKUS', 'ALPENBLICK', 'ALPENBLICK', 'GÖTZ REINIGUNGSDIENST', 'GLATT PHARMAC.', 'MONDELEZ LOERRACH', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KLINIKEN LOERRACH MBK', 'DIAKONISSEN-KH RÜPPURR', 'WARTENBERG GEISINGEN', 'SPITAL LIMMATTAL', 'HILTENSBERGER', 'MIGROS ZÜRICH', 'MIDOR', 'ABWASSERBESEITIG. STADT BS MBK', 'PFLEGEHEIM ZELL I.W.', 'BIS PROZESSTECHNIK', 'AWO WUTOESCHINGEN', 'ALLPACK', 'MONDELEZ BLUDENZ', 'NOVARTIS STEIN', 'NOVARTIS STEIN', 'JOWA HUTTWIL', 'NOVARTIS SCHWEIZERHALLE', 'HAUS EICHBERG', 'SCHÖLER FÖRDERTECHNIK', 'PH BRUNNENWIESEN', 'JOWA ECUBLENS', 'JOWA GOSSAU', 'JOWA GRÄNICHEN', 'JOWA S. ANTONINO', 'JOWA BUCHS', 'JOWA HB AARE', 'JOWA VOLKETSWIL', 'SYNGENTA KAISTEN', 'BILFINGER PROVADIS', 'VINCENTIUS STEINHÄUSER', 'MARIENKLINIK KARLSRUHE', 'VINCENTIUS SÜDENDSTR.', 'MÜHLE WILDEGG JOWA', 'WELEDA AG ARLESHEIM', 'BILFINGER ZOFINGEN', 'INTERTEK', 'KS SCHAFFHAUSEN', 'PSYCHIATRIE BREITENAU', 'PFZ SCHAFFHAUSEN', 'KLS(EHEM. DATA-MED)', 'FISHER WEIL', 'WELEDA SCHWÄB. GMÜND', 'WELEDA STERI SCHWÄB. GMÜND', 'BILFINGER HEIDENHEIM', 'AST GMBH', 'KAISER BRENNSTOFFE', 'BILFINGER EDISONSTRAßE', 'INGA WIECHS (MPH)', 'ACINO DITTINGEN', 'ISS C', 'REHACITY BASEL', 'DRK KV TUTTLINGEN', 'HEGAU PZ', 'RHEINGARTEN', 'HVB LAUBENHEIMER RI.', 'EDELBERG BAD FRIEDRICHSH.', 'EDELBERG IFFEZHEIM', 'VITALIS SCHORNDORF', 'VITALIS PLOCHINGEN', 'VITALIS TUTTLINGEN', 'ÖSCHELBRONN KLINIK', 'MIGROS VALAIS', 'MIGROS VALAIS', 'NOVARTIS KLYBECK', 'ISF GMBH', 'IOB', 'NOVARTIS ST. JOHANN', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'ST. GEORG PRIVATKL.', 'FERNBLICK HOTEL', 'RÖSSLE LANDGASTHOF', 'UNIVERSITÄTSKLINIKUM FREIB', 'UNIVERSITÄTSKLINIKUM FREIB', 'FMI FRIEDRICH MIESCHER INSTIT.', 'EDELBERG PFINZTAL', 'EDELBERG OBERDERDINGEN', 'EDELBERG LUDWIGSBURG', 'EDELBERG LAUFFEN', 'EDELBERG KERNEN', 'EDELBERG EPPELHEIM', 'EDELBERG BIETIGHEIM', 'EDELBERG BELLHEIM', 'EDELBERG KARLSRUHE', 'EDELBERG WETZGAUERBERG', 'EDELBERG STUTENSEE', 'EDELBERG NEULUßHEIM', 'EDELBERG WEINGARTEN', 'INGA RHEINWEILER', 'KB KLINIK BADENWEILER', 'KB KLINIK BADENWEILER', 'WIECHS (MPH)', 'WIECHS (MPH)', 'FFA HÜFINGEN', 'BÜRGERHEIM (BHR)', 'JESTETTEN SEN.WOHN.', 'IM BRÜEL', 'HUMANITAS', 'RHEINWEILER SCHLOSS', 'GEMEINDE BAD BELLINGEN', 'HVB KOBLENZ', 'HVB NIEDERNHAUSEN', 'HVB ULMEN', 'HVB LIMBURG', 'HVB VILLMAR', 'HVB WALLMEROD', 'UMICORE BAD SÄCKINGEN', 'MIGROS BASEL', 'HONEGGER', 'LOT GEIGER TEXTIL', 'DSM VILLAGE NEUF', 'HL-KANTINE', 'DSM SISSELN', 'DSM KAISERAUGST', 'DSM GRENZACH', 'HL KAISERAUGST', 'IDEMITSU', 'SPIROCHEM', 'BILFINGER EVIONNAZ', 'DOMACO', 'BIOGEN CBRE', 'SENEVITA EBIKON', 'SENEVITA ZOLLIKOFEN', 'SENEVITA LIMMATFELD DIETIKON', 'SENEVITA PRATTELN', 'SENEVITA SPREITENBACH', 'SENEVITA OLTEN', 'SENEVITA AARAU', 'SENEVITA PANORAMA', 'SENEVITA BÜMPLIZ', 'SENEVITA DAMMWEG', 'SENEVITA DORFMATT', 'SENEVITA GELLERTBLICK BASEL', 'VITALIS SPEYER', 'VITALIS LINGENFELD', 'VITALIS FRANKENTHAL', 'VITALIS BRUCHMÜHLBACH', 'VITALIS KLARENTHAL', 'VITALIS SAARBRÜCKEN', 'VITALIS RODALBEN', 'VITALIS ÖSTRINGEN', 'VITALIS PIRMASENS', 'ETAVIS KRIEGEL', 'GENERATIONENHAUS', 'BAAR PFLEGEZENTRUM', 'RENNBAHNKLINIK', 'SCHÖMBERG FACHKLINIK', 'SCHETTLER KLINIK', 'WEIL KLINIK', 'BAD HERRENALB KLINIK', 'SCHÖMBERG SERVICE', 'SIGMA ZENTRUM', 'OBERBERGKLINIK', 'KLS RHEINELDEN KH', 'KLS LÖRRACH', 'KLS SCHOPFHEIM', 'TEN 23 HEALTH AG', 'ESCIENTIA', 'SYNGENTA MUTTENZ', 'SMELTING', 'KDG', 'LUISENKLINIK', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'LUISENKLINIK-KIJU', 'TAGESKLINIK STUTTGART', 'PHW WEIL', 'LINDT&SPRÜ ALTENDORF', 'LINDT&SPRÜ OLTEN', 'LINDT&SPRÜ KILCHBERG', 'EMMI BEVER', 'EMMI BISCHOFSZELL DHL', 'EMMI GOSSAU DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. D-SCHWEIZ DHL', 'EMMI GR. F-SCHWEIZ DHL', 'EMMI GR. F-SCHWEIZ DHL', 'EMMI GR. F-SCHWEIZ DHL', 'EMMI GR. F-SCHWEIZ DHL', 'EMMI GR. F-SCHWEIZ DHL', 'EMMI HEFENHOFEN DHL', 'EMMI HEFENHOFEN DHL', 'EMMI LANDQUART', 'EMMI SUHR', 'EMMI ZOLLIKOFEN', 'EMMI DAGMERSELLEN', 'EMMI EMMEN', 'EMMI KALTBACH', 'EMMI KIRCHBERG', 'EMMI LANGNAU', 'EMMI OSTERMUNDIGEN', 'EMMI MÜHLAU SCHMIDLI', 'SAINT-GOBAIN', 'FELDSCHLÖSS-GETRÄNKE', 'CBRE GWS', 'GLATT GMBH', 'CELONIC', 'SCALA PH ZELL', 'SCALA ST.FRANZISKUS', 'SCALA EFRINGEN-KIRCHEN', 'BILFINGER ARNOLDT', 'HIMMELSPFORTE', 'DIAKONISSENANSTALT PFLEGE', 'DIAKONISSEN-APH BERCKHOLTZ', 'AWO KREISVERBAND BADEN', 'AWO VS', 'CBRE GETEC PARK', 'CBRE GWS C/O NOVARTIS WSJ', 'CBRE GWS C/O NOVARTIS WERK KLYBECK', 'CBRE BIOPARK WERK ROSENTHAL', 'ST. CYRIAK', 'MARGARETENHEIM LÖRRACH', 'CBRE GWS C/O NOVARTIS STEIN', 'CBRE GWS C/O LUTERBACH', 'CBRE GWS C/O CORDEN PHARMA', 'KKH SCHOPFHEIM', 'SOZIALSTATION SCHOPFHEIM', 'GEVITA MÜLLHEIM', 'GEVITA LÖRRACH', 'COLUMBAN', 'PCI BAUPROD.', 'SUNCHEMICAL MONTHEY', 'BASF ROSENTAL', 'BASF KAISTEN', 'BASF SCHWEIZERHALLE', 'BASF MONTHEY', 'BASF KLYBECK', 'SUNCHEMICAL HUNINGUE', 'HUNTSMAN KLYBECK', 'HUNTSMAN MONTHEY', 'HUNTSMAN BAD SÄCKINGEN', 'FELDSCHLÖSS-RHEINFELDEN', 'WASCHTESTS INTERN', 'BILFINGER GRENZA', 'HÖGANÄS GERMANY GMBH', 'ALUPLAST', 'BILFINGER PRATTELN', 'BILFINGER BONINGEN', 'BILFINGER SISSELN DSM', 'BILFINGER GRENZ DSM B22', 'TAKEDA NEUCHATEL ISS', 'VASCOMED', 'KLS(EHEM. DATA-MED)', 'COLUMBAN', 'GP GRENZACH PRODUKTION', 'NOVARTIS PHARMA WEHR', 'SPITAL LIMMATTAL', 'NOVARTIS STEIN', 'NOVARTIS SCHWEIZERHALLE', 'KLS(EHEM. DATA-MED)', 'NOVARTIS KLYBECK', 'NOVARTIS ST. JOHANN', 'FMI FRIEDRICH MIESCHER INSTIT.', 'FMI FRIEDRICH MIESCHER INSTIT.', 'FMI FRIEDRICH MIESCHER INSTIT.', 'RHEINWEILER SCHLOSS', 'DSM SISSELN', 'DSM GRENZACH', 'PHW WEIL', 'LINDT&SPRÜ KILCHBERG', 'BASF KAISTEN', 'BASF SCHWEIZERHALLE', 'BASF MONTHEY', 'BASF KLYBECK', 'WASCHTESTS INTERN', 'RHEINFELDEN KH', 'LANDKLINIK', 'ALTERA FRANKENTHAL', 'PH EFRINGEN-KIRCHEN', 'RHEIN JURA KLINIK', 'HÄNSLEHOF', 'HAUS AM GUGEL', 'SPITAL WALDSHUT', 'AQUALON THERME', 'RHEUMAKL.', 'WEHRAWALD', 'ST.FRANZISKUS', 'ST. ELISABETHEN KH', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH TUTTLINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'KH SPAICHINGEN', 'DIVERSE A-Z DEUTSCHLAND', 'KLINIKEN LOERRACH MBK', 'DIAKONISSEN-KH RÜPPURR', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'WARTENBERG GEISINGEN', 'SPITAL LIMMATTAL', 'MZ BRUGG', 'PFLEGEHEIM ZELL I.W.', 'AWO WUTOESCHINGEN', 'HAUS EICHBERG', 'PH BRUNNENWIESEN', 'VINCENTIUS STEINHÄUSER', 'MARIENKLINIK KARLSRUHE', 'VINCENTIUS SÜDENDSTR.', 'KS SCHAFFHAUSEN', 'HEGAU PZ', 'RHEINGARTEN', 'RHEINGARTEN', 'HVB LAUBENHEIMER RI.', 'EDELBERG BAD FRIEDRICHSH.', 'EDELBERG IFFEZHEIM', 'VITALIS SCHORNDORF', 'VITALIS PLOCHINGEN', 'ÖSCHELBRONN KLINIK', 'ST. GEORG PRIVATKL.', 'FERNBLICK HOTEL', 'RÖSSLE LANDGASTHOF', 'EDELBERG PFINZTAL', 'EDELBERG OBERDERDINGEN', 'EDELBERG LUDWIGSBURG', 'EDELBERG LAUFFEN', 'EDELBERG KERNEN', 'EDELBERG EPPELHEIM', 'EDELBERG BIETIGHEIM', 'EDELBERG BELLHEIM', 'EDELBERG KARLSRUHE', 'EDELBERG WETZGAUERBERG', 'EDELBERG STUTENSEE', 'EDELBERG NEULUßHEIM', 'EDELBERG WEINGARTEN', 'WIECHS (MPH)', 'FFA HÜFINGEN', 'JESTETTEN SEN.WOHN.', 'IM BRÜEL', 'RHEINWEILER SCHLOSS', 'HVB KOBLENZ', 'HVB NIEDERNHAUSEN', 'HVB ULMEN', 'HVB LIMBURG', 'HVB VILLMAR', 'HVB WALLMEROD', 'HVB SCHÖFFENGRUND', 'VITALIS SPEYER', 'VITALIS LINGENFELD', 'VITALIS FRANKENTHAL', 'VITALIS BRUCHMÜHLBACH', 'VITALIS KLARENTHAL', 'VITALIS SAARBRÜCKEN', 'VITALIS RODALBEN', 'VITALIS ÖSTRINGEN', 'VITALIS PIRMASENS', 'GENERATIONENHAUS', 'HOCHHAUS H21 BAAR', 'BAAR PFLEGEZENTRUM', 'RENNBAHNKLINIK', 'SCHÖMBERG FACHKLINIK', 'SCHETTLER KLINIK', 'WEIL KLINIK', 'BAD HERRENALB KLINIK', 'DOROW CLINIC LÖRRACH', 'DOROW CLINIC WALDSHUT MVZ', 'LUISENKLINIK-KIJU', 'TAGESKLINIK STUTTGART', 'PHW WEIL', 'DIAKONISSENANSTALT PFLEGE', 'AWO VS', 'MALTESER', 'ST. CYRIAK', 'MARGARETENHEIM LÖRRACH', 'MARGARETENHEIM LÖRRACH', 'KKH SCHOPFHEIM', 'KKH SCHOPFHEIM', 'KKH SCHOPFHEIM', 'COLUMBAN', 'VITA ZAHNFABRIK', 'VITA ZAHNFABRIK', 'VITA ZAHNFABRIK', 'BÜRGERHEIM (BHR)', 'LOT GEIGER TEXTIL', 'GATE GOURMET ZÜRICH', 'GATE GOURMET ZÜRICH', 'KB KLINIK BADENWEILER', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'HVB WALLMEROD', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL', 'GEIGER TEXTIL'];

   $("#kunde").autocomplete({
    source: availableTags
  });

  } );
  $("#kunde").change(function(){


var ko = $("#kunde").val();
console.log(ko);
$("#kost").modal('show');



$.ajax({

    url : 'http://192.168.40.180/post.php',
    method : 'POST',
    data : {type : "kost",daten: ko },
    success : function(request) {
      request = JSON.parse(request);
      var req = request;
      var y = 1;
       for(var x = 0; x < request.length;x++){
         y++;
         console.log(Object.values(req));
        $("#kostenst").append("<tr class='high'><td id='"+x+"' scope='col'>"+req[x][2]+"</td><td id='"+y+"' scope='col'>"+req[x][4]+"</td></tr>");
        }
        $(document).on("click", "tr.high > td", function() {
            var $this = $(this);
            if ( $this.is(":last-child") ) return;
            $(".highlight").removeClass("highlight");
            $this.parent().addClass("highlight");

            var kostens = $this.parent()[0].cells[0].innerHTML;
            $("#kostst").val(kostens);
            var ku = $("#kunde").val();
            console.log(kostens+' '+ku);

            $.ajax({

                url : 'http://192.168.40.180/post.php',
                method : 'POST',
                data : {type : "art",kunde: ku, kosten: kostens},
                success : function(request) {

                  request = JSON.parse(request);
                  var req = request;
                  console.log(req);
                  $("#koste").modal('show');
                  $('#kost').modal('hide');
                  $("#schle").click(function(){
                    $('#koste').modal('hide');
                  });
                  var s = 1;
                  for(var q = 0;q < request.length; q++){
                    s++;
                    $("#arti").append("<tr class='highe'><td id='"+q+"' scope='col'>"+req[q][0]+"</td><td id='"+s+"' scope='col'>"+req[q][1]+"</td></tr>");
                  }
                  $(document).on("click", "tr.highe > td", function() {
                      var $this = $(this);
                      if ( $this.is(":last-child") ) return;
                      $(".highlight").removeClass("highlight");
                      $this.parent().addClass("highlight");
                      var kostens = $this.parent()[0].cells[0].innerHTML;
                      $("#kostste").val(kostens);
                      $('#koste').modal('hide');
                  });


              },
                error : function(request,error)
                {
                    alert("Request: "+JSON.stringify(request));
                }

            });
        });
        $("#schl").click(function(){
          $('#kost').modal('hide');
        });
    },
    error : function(request,error)
    {
        alert("Request: "+JSON.stringify(request));
    }
});


});

  </script>
</body>
</html>
